version: '3.7'
services:
  server:
    build:
      context: ./server
    container_name: fam-app-server
    # volumes:
    #   - ./server/:/usr/src/app
    #   - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    env_file: ./server/production.env
    networks:
      - app-network
  mysql:
    image: mysql:8.0
    volumes:
      - data-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file: ./server/mysql.env
    networks:
      - app-network
  client:
    build:
      context: ./client
    container_name: fam-app-client
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local